config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :homes do
  	  resources :reviews, except: [:show, :index]
  end

  get 'pages/about'

  get 'pages/contact'

  root 'homes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :home
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:name, :address, :phone, :website, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :home_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, id: :home_address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :home_phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :website %>
    <%= form.text_field :website, id: :home_website, class: "form-control" %>
  </div>

  

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, id: :home_image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home, class: "btn btn-link" %> |
<%= link_to 'Back', homes_path, class: "btn btn-link" %>

app/views/homes/index.html.erb
 <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
      <div class="col-md-5 p-lg-5 mx-auto my-5">
        <h1 class="display-4 font-weight-normal">Sonar</h1>
        <p class="lead font-weight-normal">This app will help you collecting informations about your celebrities' favourites luxury homes.
        You can store datas based on Name, Telefone number, Address (which will automaticall connect to the exact location on Google maps) and a reference 
      website! Also don't forget to log in! ;) </p>
      </div>
      <div class="product-device shadow-sm d-none d-md-block"></div>
      <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>

<p id="notice"><%= notice %></p>

<h1>Homes</h1>

<table class="table table-hover table-condensed">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.name %></td>
        <td><%= home.address %></td>
        <td><%= home.phone %></td>
        <td><%= link_to home.website, home.website %></td>
        <td><%= link_to 'Show', home, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_home_path(home), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a new Home', new_home_path, class: "btn btn-light" %>
 
<br>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path, class: "btn btn-link" %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @home.image_url %>

<p>
  <strong>Name:</strong>
  <%= @home.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @home.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @home.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @home.website %>
</p>



<iframe
  width="300"
  height="250"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAyhh3DEecbAU4ZVjRfUzuMVoBue6le1j8
    &q=<%= @home.address.parameterize %>" allowfullscreen>
</iframe>

<%= link_to 'Edit', edit_home_path(@home), class: "btn btn-link" %> |
<%= link_to 'Back', homes_path, class: "btn btn-link" %>

app/views/layouts/_bootstrap.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<p>&copy; 2018 Michele del Monaco </p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand btn btn-light" href="/">Sonar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link btn btn-light" href="/pages/about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-light" href="/pages/contact">Contact</a>
      </li>
    </ul>
    
    <form class="form">
      <% if user_signed_in? %>
        <li><%=  link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%=  link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      <%else %> 
       <li><%=  link_to "Sign up", new_user_registration_path %></li>
       <li><%=  link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sonar</title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/bootstrap' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="container-fluid">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
  <h2>Sonar is the best way to store data of your favourite celebrities homes!</h2>
</div>

app/views/pages/contact.html.erb
<h1>We would love to hear form you!</h1>
<p>Contact us at sonareviews@sonar.com</p>